### ISSUE TITLE
GERDA database

### ISSUE THREAD

**Issue by Bargheer** [IPcommunity/field-data#1]
Hi

I am kinda new to contributing to GitHub, sorry if this is the wrong way.

For fielddata just wanted to mention the resource of the Danish GERDA database 
[link](https://eng.geus.dk/products-services-facilities/data-and-maps/national-geophysical-database-gerda)
a lot of ERT data there and since I have collected quite a bit of it, if someone is interested in a specific dataset for looking at the IP-part of this dataset there is a fair chance that I have the .raw files lying around. Just contact me and I will look into it.
This database is a bit outdated in terms of IP stuff, so far have not been able to get my DCIP inversions uploaded there in a good way, but if the ERT is there and it is later than 2015 I might have IP or know who to contact in Denmark to get whatever IP data is there, feel free to reach out to me.

Might also be interesting to use GERDA together with the drillhole database of Denmark, Jupiter
[Jupiter](https://eng.geus.dk/products-services-facilities/data-and-maps/national-well-database-jupiter)

/Arne

**Comment by halbmy** [comment]
Dear Arne, thanks for this hint. GERDA is, even though it might be 
a bit outdated, definitely a database to learn from. Would be interesting to see how many IP data there are, with at least a decent number of gates.

**Comment by Bargheer** [comment]
![image](https://github.com/IPcommunity/field-data/assets/171954992/790a552a-e40b-49d0-84b4-c8a7673fa1f7)
The first LS instrument in Denmark was introduced I think in 2010 or thereabouts, but I think I only became aware of the potential of recording the fullwaveform data from 2015 and on ... the image is a quick search of ERT lines (green color) collected since 2015, i have probably been involved in collecting 1/3-2/3 of them and have the .raw files from them lying around somewhere ... a quick guesstimate would be 500 km of ERT lines with 5m line spacing is what I have lying around.
I have been trying to tell the owners of LS instruments to collect and save the .raw files, but I am not sure how many of them did that.

**Comment by halbmy** [comment]
Anyway, this repository is not intended to save all (raw) data of all IP measurements ever, but rather a collection of well-referenced and published data sets covering a certain range of applications. I would even say here we should use processed (i.e. gated at the end) data and rather compare inversion. In the processing repository we could collect a limited number of raw data instead and compare different processing techniques.

**Comment by Bargheer** [comment]
Yes that makes a lot of sense.
I will work a bit towards finding something like this that I can maybe contribute with
